import clr
from datetime import datetime


clr.CompileModules("Manis.beta."+datetime.now().strftime("%Y.%m.%d")+".ghpy",
"analysis.py",
"anim.py",
"assembly.py",
"explode.py",
"boolean.py",
"build.py",
"chamfer.py",
"constraint.py",
"constraints.py",
"contact.py",
"contours.py",
"custom.py",
"deci.py",
"dowel.py",
"edit.py",
"faces.py",
"fem.py",
"finger.py",
"halflap.py",
"holes.py",
"insertion.py",
"joints.py",
"milling.py",
"modules.py",
"neighbours.py",
"orient.py",
"planes.py",
"platesim.py",
"scale.py",
"seqtree.py",
"spheres.py",
"stack.py",
"sunrise.py",
"tenon.py",
"text.py",
"thickness.py",
"thicken.py",
"toolpath.py",
"topology.py",
"trajectory.py")